### ISSUE TITLE
Awesome Project

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [aclueless/spair#1]
Spair looks awesome! I have been looking to mess around SPA's with wasm and this looks like a decent place to start.

I have some questions about this project.

> A framework for Single Page Application in Rust. Inspired by Simi, Mika and Yew, some parts of source are copied from them.

### What's performance expected to be in relation to simi? 

I had never heard of this library until I found them on your readme and then on [Web Framework Benchmarks](https://krausest.github.io/js-framework-benchmark/current.html). The code used for their benchmarks is 2 years old but still performs verywell, the non-keyed-duration benchmark goemetric mean score is 1.08 (vanillajs is 1.04)

### What is taken from Mika

This one is pretty new to me to but reading it's readme it looks like it's designed around signals.  I noticed spair doesn't use signals right now. Is their plans to and if so have you looked into [dominator](https://github.com/Pauan/rust-dominator) it's based around signals as well and is made by the author of [futures-signals](https://github.com/Pauan/rust-signals).

### Isomorphic

Does this project have any plans(or interest) in making isomorphic web apps?

### Benchmarks

I saw benchmarks as a goal for this project. Would you (when the project is ready) add this to [Web Framework Benchmarks](https://github.com/krausest/js-framework-benchmark)?

**Comment by aclueless** [comment]
Current goals are:
* Avoid re-rendering of the virtual DOM. So Spair is expected to be faster than Yew/Seed. But how Spair perform compare to Simi is still a question (because the implementation is different). I hope Spair perform similar to Simi, or just a little slower.
* Allow users to completely avoid macros. Unlike Simi which entirely relies on macro to generate code, Spair allow you building apps without using macros. That said, as I mentioned in README, a macro may be add later, but it must be optional, just for some users that like short syntax like JSX or Simi-style macro.
* Easy to use, may be :smile: 

> What is taken from Mika

Currently, user API is inspired by Mika. What I like most is that Mika (and Spair) **does not** use the Elm-like messages.

Yes, I looked into Dominator. But it's primarily base on signals, and I found it's a bit cumbersome to use signals in apps that not performance critical. I believe Mika try to reduce (only a half of) the cumbersome compare to Dominator.

That said, I plan to add signals (or something similar) later, and I think it just like what in Dominator (not the Mika way), but using Spair callbacks (which is based on Mika). And this will be under a Cargo feature, you only turn it on for apps that need maximum performance (hence, a little bigger binary size).

> isomorphic web apps

I have no idea about it yet. I read a discussion from Dominator issues' list and the author say it's difficult to integrate SSR (which is required for isomorphic?) to Dominator... 
Maybe in Spair we can do SSR only for non-signal-components?

> Would you (when the project is ready) add this to Web Framework Benchmarks?

Absolutely yes. Currently I have a problem with Spair callback system that I have to invest time to solve it first. After that I may find time to add some benchmarks.

**Comment by Th3Whit3Wolf** [comment]
> Avoid re-rendering of the virtual DOM. So Spair is expected to be faster than Yew/Seed. But how Spair perform compare to Simi is still a question (because the implementation is different). I hope Spair perform similar to Simi, or just a little slower

That's great to hear! I was very surprised when I saw how fast simi was, I couldn't believe it beat out all other wasm projects and most javascript projects.

> Allow users to completely avoid macros. Unlike Simi which entirely relies on macro to generate code, Spair allow you building apps without using macros. That said, as I mentioned in README, a macro may be add later, but it must be optional, just for some users that like short syntax like JSX or Simi-style macro.

Out of curiosity what is the reason for this? Does using macros create larger binaries or introduce necessary boilerplate code?

> Currently, user API is inspired by Mika. What I like most is that Mika (and Spair) does not use the Elm-like messages.

Briefly looking at the spair API I really like it! I don't do a lot of web development but spair feels much more natural than the elm inspired messages.

> Absolutely yes. Currently I have a problem with Spair callback system that I have to invest time to solve it first. After that I may find time to add some benchmarks.

That's good to hear, looking forward to seeing spair in the results!

**Comment by aclueless** [comment]
> I was very surprised when I saw how fast simi was, I couldn't believe it beat out all other wasm projects and most javascript projects.

Unfortunately, the benchmark does not enforce a standard implementation for every frameworks (including VanillaJS). All implementation that I mentions below are non-keyed because of the comparission with non-keyed-Simi.

Simi, StdWeb and VanillaJS attachs the event listeners to the **table/tbody**, while other frameworks (Elm, React and wasm frameworks Yew/Seed - just a few that I looked into its implementation) attaches the event listeners to **each row**. Therefore, benchmark's results for Simi, StdWeb, VanillaJS are comparable between them, but they are not comparable to Elm/React/Yew/Seed's results.

When implement the benchmark for Spair, I will attach event listeners to each row (in contrast to Simi - which is on the table). So, the benchmark result of Spair should be slower than what you expect.

> Out of curiosity what is the reason for this? Does using macros create larger binaries or introduce necessary boilerplate code?

Currently, `cargo fmt` does not format the code place inside a macro. To experiment, you can clone the Yew repo, open `examples/counter/src/lib.rs`, then modify it by deleting some newline chars both outside and inside of `html!`. Then run `cargo fmt` for that example, you will see modified code outside `html!` have newline added back by `cargo fmt`, but it did not happen for code inside `html!`.

It's not a big problem when you first make the code, but a problem when you refactor it. Code is created just one, but being modified many times.

Code inside a macro also has problems with auto completion and bad error messages.

> looking forward to seeing spair in the results

As I said above, Simi's benchmark give false impression compare to other frameworks. I do not know how much it's slower when attaching event listeners to every rows yet.

**Comment by Th3Whit3Wolf** [comment]
> Unfortunately, the benchmark does not enforce a standard implementation for every frameworks (including VanillaJS). All implementation that I mentions below are non-keyed because of the comparission with non-keyed-Simi.

It's a shame that consistency isn't enforced for each framework.

> Currently, cargo fmt does not format the code place inside a macro

I see, that could be a bit annoying. Thank you for all of the information!
